# Generated by Django 3.0.4 on 2020-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.AddField(
            model_name='person',
            name='adress',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='house_number',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='last_access',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='zip_code',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
